# Generated by Django 5.2.1 on 2025-05-12 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_column_remove_list_board_remove_card_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(),
        ),
    ]
